### ISSUE TITLE
How to access previous state data in buildWhen of useBlocBuilder hook

### ISSUE THREAD

**Issue by sivaram000** [Iteo/hooked_bloc#58]
Is there a way to access previous state data on buildWhen of useBlocBuilder like below:
`final state = useBlocBuilder(
    cubit,
    buildWhen: (prevState, currentState) {})`
Currently, I'm only able to access the current state and getting error when I access prevState data.

**Comment by tomkad99** [comment]
Hello @sivaram000

Thank you for your suggestion to our library. The idea has been accepted, but we don't want to create breaking change.

So everywhere in code when needed to access previous state you will have to migrate from `useBlocBuilder` to `useBlocComparativeBuilder`.

Regards
