### ISSUE TITLE
ActionCubit state should not be constrained by extends Object

### ISSUE THREAD

**Issue by KopaczPatryk** [Iteo/hooked_bloc#76]
Hey, currently you constrain the state of ActionCubit to 
```dart
abstract class ActionCubit<STATE extends Object, ACTION> extends BlocBase<STATE>
    with BlocActionMixin<ACTION, STATE> {}
```
Such thing does not allow us to define cubit that has no state yet supports dispatching actions. For example:
```dart
class TestCubit extends ActionCubit<void, SelectAction> {}
```
My request is to unconstrain this generic or move the constrain to `ACTION` type param, it should not cause any other issue.

The Bloc library itself does not constrain the state param.

**Comment by AndriiChemer** [comment]
@KopaczPatryk thx for attention. 
Version with fix: 1.4.4
https://pub.dev/packages/hooked_bloc/versions/1.4.4
